/**
 * Mission News Events
 * Scenario-specific news headlines that trigger at different days during simulations
 */

import { NewsEvent } from './missionSimulation';

export const MISSION_NEWS_EVENTS: Record<string, NewsEvent[]> = {
  neutral: [
    {
      id: 'neutral-1',
      day: 10,
      headline: 'Markets Open Higher on Positive Economic Data',
      summary: 'Jobless claims fall to 12-month low, boosting investor confidence.',
      source: 'FundThesis Markets',
      impact: 'positive',
      affectedSectors: ['Technology', 'Consumer', 'Finance'],
      priceMultiplier: 1.02,
      timestamp: new Date(),
    },
    {
      id: 'neutral-2',
      day: 25,
      headline: 'Corporate Earnings Beat Expectations',
      summary: 'S&P 500 companies report 8% earnings growth on average.',
      source: 'FundThesis Markets',
      impact: 'positive',
      affectedSectors: ['Technology', 'Healthcare', 'Consumer'],
      priceMultiplier: 1.03,
      timestamp: new Date(),
    },
    {
      id: 'neutral-3',
      day: 40,
      headline: 'Fed Maintains Current Interest Rate Policy',
      summary: 'FOMC votes unanimously to hold rates steady.',
      source: 'FundThesis Markets',
      impact: 'neutral',
      affectedSectors: ['Finance', 'Real Estate'],
      priceMultiplier: 1.0,
      timestamp: new Date(),
    },
  ],

  inflation: [
    {
      id: 'inflation-1',
      day: 5,
      headline: 'Economists Warn of Rising Inflation Pressures',
      summary: 'Consumer spending surges, raising concerns about overheating economy.',
      source: 'FundThesis Economics',
      impact: 'negative',
      affectedSectors: ['Technology', 'Consumer', 'Real Estate'],
      priceMultiplier: 0.98,
      timestamp: new Date(),
    },
    {
      id: 'inflation-2',
      day: 16,
      headline: '🔴 BREAKING: CPI Jumps 2% - Highest Reading in 18 Months',
      summary: 'Consumer Price Index shows unexpected surge in inflation, rattling markets.',
      source: 'FundThesis Breaking News',
      impact: 'negative',
      affectedSectors: ['Technology', 'Consumer', 'Real Estate', 'Finance'],
      priceMultiplier: 0.94,
      isBreaking: true,
      timestamp: new Date(),
    },
    {
      id: 'inflation-3',
      day: 20,
      headline: 'Bond Yields Spike as Inflation Fears Mount',
      summary: '10-year Treasury yield jumps 25 basis points in response to CPI data.',
      source: 'FundThesis Markets',
      impact: 'negative',
      affectedSectors: ['Real Estate', 'Utilities', 'Technology'],
      priceMultiplier: 0.96,
      timestamp: new Date(),
    },
    {
      id: 'inflation-4',
      day: 30,
      headline: 'Energy Stocks Rally on Commodity Price Surge',
      summary: 'Oil and gas companies outperform as real assets become inflation hedge.',
      source: 'FundThesis Markets',
      impact: 'positive',
      affectedSectors: ['Energy', 'Materials'],
      priceMultiplier: 1.08,
      timestamp: new Date(),
    },
    {
      id: 'inflation-5',
      day: 45,
      headline: 'TIPS Outperform Traditional Bonds',
      summary: 'Inflation-protected securities see record inflows.',
      source: 'FundThesis Markets',
      impact: 'positive',
      affectedSectors: ['Finance'],
      affectedSymbols: ['TIP', 'GLD'],
      priceMultiplier: 1.05,
      timestamp: new Date(),
    },
    {
      id: 'inflation-6',
      day: 60,
      headline: 'Fed Chair Powell: "We Have the Tools to Address Inflation"',
      summary: 'Markets stabilize as Fed signals potential rate action.',
      source: 'FundThesis Markets',
      impact: 'neutral',
      affectedSectors: ['Finance', 'Technology'],
      priceMultiplier: 1.02,
      timestamp: new Date(),
    },
    {
      id: 'inflation-7',
      day: 80,
      headline: 'Inflation Shows Signs of Peaking',
      summary: 'Month-over-month CPI increase slows, offering relief.',
      source: 'FundThesis Economics',
      impact: 'positive',
      affectedSectors: ['Technology', 'Consumer', 'Real Estate'],
      priceMultiplier: 1.04,
      timestamp: new Date(),
    },
  ],

  'rate-cut': [
    {
      id: 'ratecut-1',
      day: 5,
      headline: 'Weak Jobs Report Sparks Rate Cut Speculation',
      summary: 'Unemployment ticks higher, raising hopes for Fed action.',
      source: 'FundThesis Economics',
      impact: 'positive',
      affectedSectors: ['Technology', 'Real Estate', 'Consumer'],
      priceMultiplier: 1.02,
      timestamp: new Date(),
    },
    {
      id: 'ratecut-2',
      day: 15,
      headline: 'Fed Officials Signal Dovish Pivot Ahead',
      summary: 'Multiple governors express openness to rate cuts.',
      source: 'FundThesis Markets',
      impact: 'positive',
      affectedSectors: ['Technology', 'Real Estate', 'Consumer'],
      priceMultiplier: 1.03,
      timestamp: new Date(),
    },
    {
      id: 'ratecut-3',
      day: 21,
      headline: '🔴 BREAKING: FOMC Announces 50 Basis Point Rate Cut',
      summary: 'Federal Reserve cuts target rate by 0.50%, larger than expected.',
      source: 'FundThesis Breaking News',
      impact: 'positive',
      affectedSectors: ['Technology', 'Real Estate', 'Consumer', 'Finance'],
      priceMultiplier: 1.06,
      isBreaking: true,
      timestamp: new Date(),
    },
    {
      id: 'ratecut-4',
      day: 25,
      headline: 'Bond Prices Surge as Yields Tumble',
      summary: 'Fixed income markets rally on dovish Fed stance.',
      source: 'FundThesis Markets',
      impact: 'positive',
      affectedSectors: ['Real Estate', 'Utilities'],
      priceMultiplier: 1.04,
      timestamp: new Date(),
    },
    {
      id: 'ratecut-5',
      day: 35,
      headline: 'Banks Face Margin Pressure from Lower Rates',
      summary: 'Financial sector underperforms as net interest margins compress.',
      source: 'FundThesis Markets',
      impact: 'negative',
      affectedSectors: ['Finance'],
      affectedSymbols: ['JPM', 'BAC'],
      priceMultiplier: 0.95,
      timestamp: new Date(),
    },
    {
      id: 'ratecut-6',
      day: 50,
      headline: 'Tech Giants Hit All-Time Highs',
      summary: 'Growth stocks surge on lower discount rates.',
      source: 'FundThesis Markets',
      impact: 'positive',
      affectedSectors: ['Technology'],
      affectedSymbols: ['NVDA', 'MSFT', 'GOOGL'],
      priceMultiplier: 1.08,
      timestamp: new Date(),
    },
    {
      id: 'ratecut-7',
      day: 70,
      headline: 'Real Estate Sector Leads Market Rally',
      summary: 'Lower borrowing costs boost property valuations.',
      source: 'FundThesis Markets',
      impact: 'positive',
      affectedSectors: ['Real Estate'],
      affectedSymbols: ['AMT'],
      priceMultiplier: 1.06,
      timestamp: new Date(),
    },
  ],

  'currency-weak': [
    {
      id: 'currency-1',
      day: 10,
      headline: 'Dollar Index Slides on Trade Deficit Data',
      summary: 'USD weakens as trade gap widens to 5-year high.',
      source: 'FundThesis Economics',
      impact: 'neutral',
      affectedSectors: ['Industrial', 'Technology'],
      priceMultiplier: 1.01,
      timestamp: new Date(),
    },
    {
      id: 'currency-2',
      day: 25,
      headline: 'Euro, Yen Strengthen Against Dollar',
      summary: 'Major currencies gain 3-5% against USD.',
      source: 'FundThesis Markets',
      impact: 'neutral',
      affectedSectors: ['Consumer', 'Technology'],
      priceMultiplier: 1.0,
      timestamp: new Date(),
    },
    {
      id: 'currency-3',
      day: 35,
      headline: '🔴 BREAKING: Dollar Falls 10% Against Currency Basket',
      summary: 'Sharp devaluation sends shockwaves through global markets.',
      source: 'FundThesis Breaking News',
      impact: 'negative',
      affectedSectors: ['Finance', 'Consumer'],
      priceMultiplier: 0.94,
      isBreaking: true,
      timestamp: new Date(),
    },
    {
      id: 'currency-4',
      day: 45,
      headline: 'Multinational Earnings Surge on Currency Tailwind',
      summary: 'Companies with overseas revenue see profits jump.',
      source: 'FundThesis Markets',
      impact: 'positive',
      affectedSectors: ['Technology', 'Industrial', 'Healthcare'],
      affectedSymbols: ['MSFT', 'AAPL', 'CAT', 'JNJ'],
      priceMultiplier: 1.08,
      timestamp: new Date(),
    },
    {
      id: 'currency-5',
      day: 60,
      headline: 'Gold Hits Record High as Dollar Tumbles',
      summary: 'Precious metals rally on safe-haven demand.',
      source: 'FundThesis Markets',
      impact: 'positive',
      affectedSectors: ['Materials'],
      affectedSymbols: ['GLD'],
      priceMultiplier: 1.12,
      timestamp: new Date(),
    },
    {
      id: 'currency-6',
      day: 80,
      headline: 'International ETFs Outperform Domestic Funds',
      summary: 'Weak dollar boosts returns for foreign holdings.',
      source: 'FundThesis Markets',
      impact: 'positive',
      affectedSectors: ['Finance'],
      affectedSymbols: ['EFA'],
      priceMultiplier: 1.07,
      timestamp: new Date(),
    },
    {
      id: 'currency-7',
      day: 100,
      headline: 'Fed Intervenes to Stabilize Dollar',
      summary: 'Central bank action halts currency slide.',
      source: 'FundThesis Markets',
      impact: 'positive',
      affectedSectors: ['Finance', 'Consumer'],
      priceMultiplier: 1.03,
      timestamp: new Date(),
    },
  ],

  tariff: [
    {
      id: 'tariff-1',
      day: 5,
      headline: 'Trade Tensions Escalate Between US and China',
      summary: 'White House officials hint at new tariff measures.',
      source: 'FundThesis Politics',
      impact: 'negative',
      affectedSectors: ['Technology', 'Consumer', 'Industrial'],
      priceMultiplier: 0.97,
      timestamp: new Date(),
    },
    {
      id: 'tariff-2',
      day: 15,
      headline: 'Supply Chain Executives Warn of Tariff Impact',
      summary: 'Major retailers voice concerns over potential price increases.',
      source: 'FundThesis Business',
      impact: 'negative',
      affectedSectors: ['Consumer', 'Technology'],
      affectedSymbols: ['WMT', 'AMZN', 'AAPL'],
      priceMultiplier: 0.96,
      timestamp: new Date(),
    },
    {
      id: 'tariff-3',
      day: 22,
      headline: '🔴 BREAKING: US Imposes 50% Tariff on Chinese Electronics',
      summary: 'Sweeping tariffs hit all Chinese-manufactured tech products.',
      source: 'FundThesis Breaking News',
      impact: 'negative',
      affectedSectors: ['Technology', 'Consumer'],
      affectedSymbols: ['AAPL', 'NVDA', 'WMT', 'AMZN'],
      priceMultiplier: 0.88,
      isBreaking: true,
      timestamp: new Date(),
    },
    {
      id: 'tariff-4',
      day: 28,
      headline: 'China Retaliates with Counter-Tariffs',
      summary: 'Beijing announces tariffs on US agriculture and machinery.',
      source: 'FundThesis Breaking News',
      impact: 'negative',
      affectedSectors: ['Industrial', 'Materials'],
      affectedSymbols: ['CAT', 'BA'],
      priceMultiplier: 0.92,
      isBreaking: true,
      timestamp: new Date(),
    },
    {
      id: 'tariff-5',
      day: 40,
      headline: 'Domestic Semiconductor Firms Rally on "America First" Push',
      summary: 'US-based chip makers see surge in reshoring demand.',
      source: 'FundThesis Markets',
      impact: 'positive',
      affectedSectors: ['Technology'],
      priceMultiplier: 1.06,
      timestamp: new Date(),
    },
    {
      id: 'tariff-6',
      day: 60,
      headline: 'Consumer Prices Rise as Tariffs Take Effect',
      summary: 'Electronics and retail goods see 5-15% price increases.',
      source: 'FundThesis Economics',
      impact: 'negative',
      affectedSectors: ['Consumer'],
      priceMultiplier: 0.95,
      timestamp: new Date(),
    },
    {
      id: 'tariff-7',
      day: 90,
      headline: 'Trade Talks Resume as Both Sides Seek De-escalation',
      summary: 'Negotiators return to table, markets cautiously optimistic.',
      source: 'FundThesis Politics',
      impact: 'positive',
      affectedSectors: ['Technology', 'Consumer', 'Industrial'],
      priceMultiplier: 1.05,
      timestamp: new Date(),
    },
    {
      id: 'tariff-8',
      day: 110,
      headline: 'Partial Trade Deal Reached',
      summary: 'Some tariffs to be reduced, markets rally.',
      source: 'FundThesis Breaking News',
      impact: 'positive',
      affectedSectors: ['Technology', 'Consumer', 'Industrial'],
      priceMultiplier: 1.08,
      isBreaking: true,
      timestamp: new Date(),
    },
  ],

  merger: [
    {
      id: 'merger-1',
      day: 5,
      headline: 'Consolidation Rumors Swirl in Tech Sector',
      summary: 'Analysts speculate on potential mega-deals.',
      source: 'FundThesis Markets',
      impact: 'neutral',
      affectedSectors: ['Technology'],
      priceMultiplier: 1.01,
      timestamp: new Date(),
    },
    {
      id: 'merger-2',
      day: 11,
      headline: '🔴 BREAKING: Major Acquisition Announced at 30% Premium',
      summary: 'Tech giant offers massive premium for mid-cap target.',
      source: 'FundThesis Breaking News',
      impact: 'positive',
      affectedSectors: ['Technology'],
      affectedSymbols: ['META'], // Target stock
      priceMultiplier: 1.28,
      isBreaking: true,
      timestamp: new Date(),
    },
    {
      id: 'merger-3',
      day: 13,
      headline: 'Merger Arbitrageurs Pile Into Target Stock',
      summary: 'Hedge funds see spread opportunity in pending deal.',
      source: 'FundThesis Markets',
      impact: 'positive',
      affectedSectors: ['Technology'],
      priceMultiplier: 1.02,
      timestamp: new Date(),
    },
    {
      id: 'merger-4',
      day: 25,
      headline: 'FTC Announces Review of Proposed Merger',
      summary: 'Regulatory scrutiny creates uncertainty.',
      source: 'FundThesis Business',
      impact: 'negative',
      affectedSectors: ['Technology'],
      priceMultiplier: 0.95,
      timestamp: new Date(),
    },
    {
      id: 'merger-5',
      day: 40,
      headline: 'Deal Terms Renegotiated, Premium Reduced',
      summary: 'Acquirer revises offer amid market volatility.',
      source: 'FundThesis Markets',
      impact: 'negative',
      affectedSectors: ['Technology'],
      priceMultiplier: 0.93,
      timestamp: new Date(),
    },
    {
      id: 'merger-6',
      day: 55,
      headline: 'Merger Receives Regulatory Approval',
      summary: 'FTC clears deal with minor conditions.',
      source: 'FundThesis Breaking News',
      impact: 'positive',
      affectedSectors: ['Technology'],
      priceMultiplier: 1.06,
      isBreaking: true,
      timestamp: new Date(),
    },
  ],

  bubble: [
    {
      id: 'bubble-1',
      day: 5,
      headline: 'AI Stocks Surge on Breakthrough Announcement',
      summary: 'New large language model sparks investor frenzy.',
      source: 'FundThesis Technology',
      impact: 'positive',
      affectedSectors: ['Technology'],
      affectedSymbols: ['NVDA', 'MSFT', 'GOOGL', 'META'],
      priceMultiplier: 1.08,
      timestamp: new Date(),
    },
    {
      id: 'bubble-2',
      day: 15,
      headline: 'Every Company Now an "AI Company"',
      summary: 'Stocks jump 20% just by adding AI to their names.',
      source: 'FundThesis Markets',
      impact: 'positive',
      affectedSectors: ['Technology'],
      priceMultiplier: 1.15,
      timestamp: new Date(),
    },
    {
      id: 'bubble-3',
      day: 25,
      headline: 'Retail Investors Pile Into AI Stocks',
      summary: 'Social media drives record trading volumes.',
      source: 'FundThesis Markets',
      impact: 'positive',
      affectedSectors: ['Technology'],
      priceMultiplier: 1.12,
      timestamp: new Date(),
    },
    {
      id: 'bubble-4',
      day: 35,
      headline: 'AI Valuations Reach "Dot-Com Levels"',
      summary: 'Analysts warn of excessive speculation.',
      source: 'FundThesis Analysis',
      impact: 'neutral',
      affectedSectors: ['Technology'],
      priceMultiplier: 1.05,
      timestamp: new Date(),
    },
    {
      id: 'bubble-5',
      day: 45,
      headline: 'NVIDIA Reports Record Earnings, Stock Gaps Up 20%',
      summary: 'Data center demand exceeds all expectations.',
      source: 'FundThesis Markets',
      impact: 'positive',
      affectedSectors: ['Technology'],
      affectedSymbols: ['NVDA'],
      priceMultiplier: 1.20,
      timestamp: new Date(),
    },
    {
      id: 'bubble-6',
      day: 52,
      headline: 'Hedge Funds Start Quietly Reducing AI Exposure',
      summary: 'Institutional selling detected in options markets.',
      source: 'FundThesis Analysis',
      impact: 'negative',
      affectedSectors: ['Technology'],
      priceMultiplier: 0.95,
      timestamp: new Date(),
    },
    {
      id: 'bubble-7',
      day: 58,
      headline: '"Wrapper" AI Companies Face Skepticism',
      summary: 'Investors question sustainability of businesses built on OpenAI.',
      source: 'FundThesis Technology',
      impact: 'negative',
      affectedSectors: ['Technology'],
      priceMultiplier: 0.88,
      timestamp: new Date(),
    },
    {
      id: 'bubble-8',
      day: 65,
      headline: '🔴 BREAKING: AI Bubble Bursts - Tech Stocks Plunge',
      summary: 'Nasdaq drops 8% in single session as reality check hits.',
      source: 'FundThesis Breaking News',
      impact: 'negative',
      affectedSectors: ['Technology'],
      priceMultiplier: 0.78,
      isBreaking: true,
      timestamp: new Date(),
    },
    {
      id: 'bubble-9',
      day: 75,
      headline: 'Flight to Quality as Investors Seek Safe Havens',
      summary: 'Dividend stocks and bonds rally amid tech selloff.',
      source: 'FundThesis Markets',
      impact: 'positive',
      affectedSectors: ['Healthcare', 'Consumer', 'Energy'],
      affectedSymbols: ['JNJ', 'XOM', 'CVX'],
      priceMultiplier: 1.06,
      timestamp: new Date(),
    },
    {
      id: 'bubble-10',
      day: 85,
      headline: 'Real AI Winners Emerge from the Wreckage',
      summary: 'Companies with actual revenue growth stabilize.',
      source: 'FundThesis Analysis',
      impact: 'positive',
      affectedSectors: ['Technology'],
      affectedSymbols: ['NVDA', 'MSFT'],
      priceMultiplier: 1.08,
      timestamp: new Date(),
    },
  ],

  pandemic: [
    {
      id: 'pandemic-1',
      day: 3,
      headline: 'Unusual Illness Cluster Reported in Taiwan',
      summary: 'Health officials monitor respiratory illness in tech hub.',
      source: 'FundThesis World',
      impact: 'neutral',
      affectedSectors: ['Technology'],
      priceMultiplier: 0.99,
      timestamp: new Date(),
    },
    {
      id: 'pandemic-2',
      day: 8,
      headline: 'TSMC Employees Report Sick, Production Slows',
      summary: 'World\'s largest chipmaker sees absenteeism spike.',
      source: 'FundThesis Technology',
      impact: 'negative',
      affectedSectors: ['Technology'],
      affectedSymbols: ['NVDA', 'AAPL'],
      priceMultiplier: 0.94,
      timestamp: new Date(),
    },
    {
      id: 'pandemic-3',
      day: 12,
      headline: '🔴 BREAKING: Taiwan Announces 30-Day Fab Lockdown',
      summary: 'Hsinchu and Tainan tech hubs under mandatory quarantine.',
      source: 'FundThesis Breaking News',
      impact: 'negative',
      affectedSectors: ['Technology', 'Consumer'],
      affectedSymbols: ['NVDA', 'AAPL', 'AMZN'],
      priceMultiplier: 0.85,
      isBreaking: true,
      timestamp: new Date(),
    },
    {
      id: 'pandemic-4',
      day: 18,
      headline: 'Global Chip Shortage Intensifies',
      summary: 'Auto makers and electronics firms warn of production halts.',
      source: 'FundThesis Business',
      impact: 'negative',
      affectedSectors: ['Technology', 'Industrial', 'Consumer'],
      priceMultiplier: 0.92,
      timestamp: new Date(),
    },
    {
      id: 'pandemic-5',
      day: 30,
      headline: 'Tech Stocks Hit Multi-Month Lows',
      summary: 'Supply chain fears dominate market sentiment.',
      source: 'FundThesis Markets',
      impact: 'negative',
      affectedSectors: ['Technology'],
      priceMultiplier: 0.90,
      timestamp: new Date(),
    },
    {
      id: 'pandemic-6',
      day: 42,
      headline: 'Domestic Chip Alternatives Rally',
      summary: 'US and European semiconductor firms see demand surge.',
      source: 'FundThesis Markets',
      impact: 'positive',
      affectedSectors: ['Technology'],
      priceMultiplier: 1.06,
      timestamp: new Date(),
    },
    {
      id: 'pandemic-7',
      day: 48,
      headline: 'Taiwan Lockdown Extended by 15 Days',
      summary: 'Outbreak not yet contained, markets sink.',
      source: 'FundThesis Breaking News',
      impact: 'negative',
      affectedSectors: ['Technology'],
      priceMultiplier: 0.93,
      isBreaking: true,
      timestamp: new Date(),
    },
    {
      id: 'pandemic-8',
      day: 55,
      headline: 'Infection Rates Plateau in Taiwan',
      summary: 'Health officials see light at end of tunnel.',
      source: 'FundThesis World',
      impact: 'positive',
      affectedSectors: ['Technology'],
      priceMultiplier: 1.04,
      timestamp: new Date(),
    },
    {
      id: 'pandemic-9',
      day: 62,
      headline: '🔴 BREAKING: Taiwan Fabs Resume Production',
      summary: 'Lockdown lifted, manufacturing to restart in phases.',
      source: 'FundThesis Breaking News',
      impact: 'positive',
      affectedSectors: ['Technology', 'Consumer'],
      affectedSymbols: ['NVDA', 'AAPL', 'AMZN'],
      priceMultiplier: 1.10,
      isBreaking: true,
      timestamp: new Date(),
    },
    {
      id: 'pandemic-10',
      day: 80,
      headline: 'Supply Chain Recovery Faster Than Expected',
      summary: 'Chip supply normalizing, backlogs clearing.',
      source: 'FundThesis Business',
      impact: 'positive',
      affectedSectors: ['Technology', 'Industrial', 'Consumer'],
      priceMultiplier: 1.06,
      timestamp: new Date(),
    },
  ],

  'crash-2008': [
    {
      id: 'crash-1',
      day: 1,
      headline: '🔴 BREAKING: Lehman Brothers Files for Bankruptcy',
      summary: 'Fourth-largest investment bank collapses, markets in chaos.',
      source: 'FundThesis Breaking News',
      impact: 'negative',
      affectedSectors: ['Finance', 'Real Estate'],
      affectedSymbols: ['JPM', 'BAC'],
      priceMultiplier: 0.88,
      isBreaking: true,
      timestamp: new Date(),
    },
    {
      id: 'crash-2',
      day: 10,
      headline: 'AIG Bailout Announced - $85 Billion Fed Loan',
      summary: 'Government steps in to prevent insurance giant collapse.',
      source: 'FundThesis Breaking News',
      impact: 'negative',
      affectedSectors: ['Finance'],
      priceMultiplier: 0.92,
      isBreaking: true,
      timestamp: new Date(),
    },
    {
      id: 'crash-3',
      day: 20,
      headline: 'Credit Markets Freeze, Interbank Lending Halts',
      summary: 'Banks refuse to lend to each other amid counterparty fears.',
      source: 'FundThesis Markets',
      impact: 'negative',
      affectedSectors: ['Finance', 'Consumer', 'Industrial'],
      priceMultiplier: 0.85,
      timestamp: new Date(),
    },
    {
      id: 'crash-4',
      day: 35,
      headline: 'Dow Suffers Worst Single-Day Point Drop Ever',
      summary: 'Markets plunge as panic selling takes hold.',
      source: 'FundThesis Breaking News',
      impact: 'negative',
      affectedSectors: ['Technology', 'Finance', 'Consumer', 'Industrial'],
      priceMultiplier: 0.88,
      isBreaking: true,
      timestamp: new Date(),
    },
    {
      id: 'crash-5',
      day: 50,
      headline: 'Housing Prices Continue Free Fall',
      summary: 'Foreclosures surge to record levels nationwide.',
      source: 'FundThesis Economics',
      impact: 'negative',
      affectedSectors: ['Real Estate', 'Finance'],
      priceMultiplier: 0.90,
      timestamp: new Date(),
    },
    {
      id: 'crash-6',
      day: 70,
      headline: 'Global Markets in Coordinated Selloff',
      summary: 'Financial contagion spreads to Europe and Asia.',
      source: 'FundThesis World',
      impact: 'negative',
      affectedSectors: ['Technology', 'Finance', 'Consumer', 'Industrial'],
      priceMultiplier: 0.88,
      timestamp: new Date(),
    },
    {
      id: 'crash-7',
      day: 85,
      headline: 'Market Hits Bottom - S&P 500 Down 50% from Peak',
      summary: 'Historic capitulation as fear reaches maximum.',
      source: 'FundThesis Markets',
      impact: 'negative',
      affectedSectors: ['Technology', 'Finance', 'Consumer', 'Industrial'],
      priceMultiplier: 0.92,
      timestamp: new Date(),
    },
    {
      id: 'crash-8',
      day: 95,
      headline: '🔴 BREAKING: Congress Passes $700B TARP Bailout',
      summary: 'Troubled Asset Relief Program signed into law.',
      source: 'FundThesis Breaking News',
      impact: 'positive',
      affectedSectors: ['Finance'],
      priceMultiplier: 1.08,
      isBreaking: true,
      timestamp: new Date(),
    },
    {
      id: 'crash-9',
      day: 110,
      headline: 'Fed Launches Quantitative Easing Program',
      summary: 'Central bank to buy mortgage-backed securities.',
      source: 'FundThesis Breaking News',
      impact: 'positive',
      affectedSectors: ['Finance', 'Real Estate'],
      priceMultiplier: 1.06,
      isBreaking: true,
      timestamp: new Date(),
    },
    {
      id: 'crash-10',
      day: 130,
      headline: 'Tentative Signs of Market Stabilization',
      summary: 'Volatility begins to decline, buyers emerge.',
      source: 'FundThesis Markets',
      impact: 'positive',
      affectedSectors: ['Technology', 'Consumer'],
      priceMultiplier: 1.05,
      timestamp: new Date(),
    },
    {
      id: 'crash-11',
      day: 150,
      headline: 'Warren Buffett: "Be Greedy When Others Are Fearful"',
      summary: 'Oracle of Omaha sees buying opportunity.',
      source: 'FundThesis Markets',
      impact: 'positive',
      affectedSectors: ['Finance', 'Consumer', 'Industrial'],
      priceMultiplier: 1.04,
      timestamp: new Date(),
    },
    {
      id: 'crash-12',
      day: 170,
      headline: 'Market Rally Gains Momentum',
      summary: 'S&P 500 up 20% from March lows.',
      source: 'FundThesis Markets',
      impact: 'positive',
      affectedSectors: ['Technology', 'Finance', 'Consumer'],
      priceMultiplier: 1.06,
      timestamp: new Date(),
    },
  ],

  'live-news': [
    {
      id: 'live-1',
      day: 2,
      headline: '🔴 BREAKING: Major Tech Company Beats Earnings',
      summary: 'Revenue up 15%, guidance raised for next quarter.',
      source: 'FundThesis Breaking News',
      impact: 'positive',
      affectedSectors: ['Technology'],
      priceMultiplier: 1.06,
      isBreaking: true,
      timestamp: new Date(),
    },
    {
      id: 'live-2',
      day: 5,
      headline: 'Fed Official Hints at Policy Shift',
      summary: 'Markets react to dovish comments.',
      source: 'FundThesis Markets',
      impact: 'positive',
      affectedSectors: ['Technology', 'Real Estate'],
      priceMultiplier: 1.03,
      timestamp: new Date(),
    },
    {
      id: 'live-3',
      day: 10,
      headline: '🔴 BREAKING: Geopolitical Tensions Escalate',
      summary: 'Safe haven assets rally on uncertainty.',
      source: 'FundThesis Breaking News',
      impact: 'negative',
      affectedSectors: ['Technology', 'Consumer'],
      affectedSymbols: ['GLD'],
      priceMultiplier: 0.96,
      isBreaking: true,
      timestamp: new Date(),
    },
    {
      id: 'live-4',
      day: 15,
      headline: 'Jobs Report Stronger Than Expected',
      summary: 'Unemployment falls, wage growth accelerates.',
      source: 'FundThesis Economics',
      impact: 'positive',
      affectedSectors: ['Consumer', 'Finance'],
      priceMultiplier: 1.04,
      timestamp: new Date(),
    },
    {
      id: 'live-5',
      day: 20,
      headline: '🔴 BREAKING: Major Retailer Misses Holiday Sales',
      summary: 'Consumer spending concerns weigh on markets.',
      source: 'FundThesis Breaking News',
      impact: 'negative',
      affectedSectors: ['Consumer'],
      affectedSymbols: ['WMT', 'AMZN', 'COST'],
      priceMultiplier: 0.94,
      isBreaking: true,
      timestamp: new Date(),
    },
    {
      id: 'live-6',
      day: 25,
      headline: 'Energy Prices Spike on Supply Disruption',
      summary: 'Oil jumps 8% on pipeline issues.',
      source: 'FundThesis Markets',
      impact: 'positive',
      affectedSectors: ['Energy'],
      affectedSymbols: ['XOM', 'CVX'],
      priceMultiplier: 1.08,
      timestamp: new Date(),
    },
    {
      id: 'live-7',
      day: 28,
      headline: '🔴 BREAKING: Surprise FDA Approval Boosts Pharma',
      summary: 'Healthcare stocks rally on drug approval.',
      source: 'FundThesis Breaking News',
      impact: 'positive',
      affectedSectors: ['Healthcare'],
      affectedSymbols: ['JNJ', 'UNH'],
      priceMultiplier: 1.06,
      isBreaking: true,
      timestamp: new Date(),
    },
  ],
};

/**
 * Get news events for a specific mission scenario
 */
export function getMissionNewsEvents(scenario: string): NewsEvent[] {
  return MISSION_NEWS_EVENTS[scenario] || MISSION_NEWS_EVENTS.neutral;
}

/**
 * Get triggered events up to a specific day
 */
export function getTriggeredEvents(scenario: string, currentDay: number): NewsEvent[] {
  const events = getMissionNewsEvents(scenario);
  return events.filter(event => event.day <= currentDay);
}

/**
 * Get the most recent event for display
 */
export function getMostRecentEvent(scenario: string, currentDay: number): NewsEvent | null {
  const events = getTriggeredEvents(scenario, currentDay);
  if (events.length === 0) return null;
  return events[events.length - 1];
}

/**
 * Check if there's a new event on this day
 */
export function hasNewEventOnDay(scenario: string, day: number): boolean {
  const events = getMissionNewsEvents(scenario);
  return events.some(event => event.day === day);
}

/**
 * Get events on a specific day
 */
export function getEventsOnDay(scenario: string, day: number): NewsEvent[] {
  const events = getMissionNewsEvents(scenario);
  return events.filter(event => event.day === day);
}
